export const FETCH_PRODUCTDATA_REQUEST = 'FETCH_PRODUCTDATA_REQUEST'
export const FETCH_PRODUCTDATA_SUCCESS = 'FETCH_PRODUCTDATA_SUCCESS'
export const FETCH_PRODUCTDATA_FAILURE = 'FETCH_PRODUCTDATA_FAILURE'
